import React from 'react';
import { Card } from '../components';

export default function TermsOfUsePage({ setPage }) {
    return (
        <div className="bg-white text-gray-800">
            {/* Header */}
            <header className="bg-white/30 backdrop-blur-lg shadow-sm sticky top-0 z-50">
                <div className="container mx-auto px-6 py-4 flex justify-between items-center">
                    <div className="flex items-center space-x-3">
                        <button onClick={() => setPage('landing')} className="flex items-center space-x-3">
                            <img src="https://i.ibb.co/YB8HrVsD/VALogo1.png" alt="VA Claims Pro Logo" className="h-12 w-auto" />
                        </button>
                    </div>
                    <div className="flex items-center space-x-4">
                        <button onClick={() => setPage('login')} className="text-gray-600 hover:text-[#c62727] font-semibold text-sm">
                            Login
                        </button>
                        <button onClick={() => setPage('signup')} className="cta-button bg-[#c62727] text-white font-semibold py-2 px-5 rounded-lg text-sm shadow-md hover:bg-red-800 transition-colors">
                            Get Started Free
                        </button>
                    </div>
                </div>
            </header>

            {/* Main Content */}
            <main className="max-w-6xl mx-auto px-4 py-16">
                <Card title="LEGAL DISCLOSURE AND TERMS OF USE">
                    <div className="p-6 space-y-6 text-slate-600 dark:text-slate-300 prose dark:prose-invert max-w-none">
                        <h2 className="font-bold text-xl text-slate-800 dark:text-slate-100">Important Notice: VAClaimsPro Is Not VA-Accredited</h2>
                        <p>VAClaimsPro is an independent organization and is not accredited by the U.S. Department of Veterans Affairs (VA). We want our users to be completely informed—VAClaimsPro is not affiliated with or endorsed by the VA. Our company, staff, and AI platform cannot act as your representative with the VA. As such, we do not:</p>
                        <ul>
                            <li>Submit or file VA claims for you</li>
                            <li>Collect or prepare evidence on your behalf</li>
                            <li>Communicate with the VA in any official capacity</li>
                            <li>Offer legal counsel or advice on your VA claim</li>
                        </ul>
                        <p>By using VAClaimsPro, you agree to the following terms and conditions. If you do not agree, please do not use our platform.</p>

                        <h2 className="font-bold text-xl text-slate-800 dark:text-slate-100">1. For Educational Purposes Only</h2>
                        <p>All content, tools, and information provided by VAClaimsPro—including anything generated by our AI platform—are for general educational purposes about the VA disability system and related processes. This information is not a substitute for legal, medical, or financial advice from licensed professionals. We do not guarantee the completeness or accuracy of any content for your specific circumstances.</p>

                        <h2 className="font-bold text-xl text-slate-800 dark:text-slate-100">2. User’s Responsibility</h2>
                        <p>You are solely responsible for your own research and for any actions you take based on information from this platform. You should independently verify all information before making decisions regarding your VA claim, medical care, or financial matters. VAClaimsPro assumes no liability for errors or omissions in our content or for consequences of actions taken based on information from this platform.</p>

                        <h2 className="font-bold text-xl text-slate-800 dark:text-slate-100">3. Tools for Self-Directed Exploration Only</h2>
                        <p>Our platform offers tools designed to help you explore possible connections between service-related conditions based on your own input and research. The information provided does not constitute medical advice, a diagnosis, legal advice, or a guarantee of VA benefits eligibility. Results and recommendations are meant for your personal use and to support your conversations with qualified experts.</p>

                        <h2 className="font-bold text-xl text-slate-800 dark:text-slate-100">4. Tool Limitations and No Guarantee of Accuracy</h2>
                        <p>The effectiveness of our platform depends entirely on the accuracy and completeness of the information you provide. VAClaimsPro does not warrant that its tools will be error-free, current, or suitable for every purpose. VA regulations and benefits programs are complex and may change at any time.</p>

                        <h2 className="font-bold text-xl text-slate-800 dark:text-slate-100">5. No Endorsement or Guarantee of Outcome</h2>
                        <p>VAClaimsPro cannot guarantee, endorse, or influence the approval of your VA claim. All eligibility and benefit decisions are made exclusively by the U.S. Department of Veterans Affairs and are based on the specifics of each case. Use of our platform does not increase the likelihood of claim approval.</p>

                        <h2 className="font-bold text-xl text-slate-800 dark:text-slate-100">6. Limitation of Liability</h2>
                        <p>To the maximum extent allowed by law, VAClaimsPro and its team disclaim all liability for any direct or indirect damages arising from your use of this platform—including, but not limited to, loss of profits, data, or other intangible losses.</p>

                        <h2 className="font-bold text-xl text-slate-800 dark:text-slate-100">7. Indemnification</h2>
                        <p>By using VAClaimsPro, you agree to indemnify and hold harmless our company, employees, contractors, and affiliates against any claims, damages, or losses arising from your use of the platform or violation of these terms.</p>

                        <h2 className="font-bold text-xl text-slate-800 dark:text-slate-100">8. Governing Law and Dispute Resolution</h2>
                        <p>This agreement is governed by the laws of the Commonwealth of Virginia. Any disputes will be resolved by binding arbitration in accordance with the American Arbitration Association.</p>

                        <h2 className="font-bold text-xl text-slate-800 dark:text-slate-100">9. Professional Support Recommendation</h2>
                        <p>If you need help filing a VA claim or appealing a decision, we recommend contacting a VA-accredited attorney, claims agent, or Veterans Service Organization (VSO). Accredited representatives can be found through the official VA website.</p>
                    </div>
                </Card>
            </main>

            {/* Footer */}
            <footer className="bg-[#002458] text-white py-16">
                <div className="container mx-auto px-6 text-center">
                    <img src="https://i.ibb.co/75002Dq/VAClaims-Logo-WHITE.png" alt="VA Claims Pro Logo" className="h-12 w-auto mx-auto mb-4" />
                    <p className="text-gray-400 max-w-xl mx-auto mb-8">Ready to Find Out What You’re Owed? Don’t settle. Don’t wonder. Take control of your VA claim—today.</p>
                    <div className="flex justify-center items-center gap-4 mb-8">
                        <button onClick={() => setPage('signup')} className="cta-button bg-[#c62727] text-white font-bold py-3 px-8 rounded-lg text-base shadow-xl">
                            Try VAClaimsPro Free
                        </button>
                    </div>
                    <div className="flex justify-center space-x-6 mb-8 text-sm">
                        <button onClick={() => setPage('landing')} className="text-gray-300 hover:text-white">Home</button>
                        <button onClick={() => setPage('privacy')} className="text-gray-300 hover:text-white">Privacy Policy</button>
                        <button onClick={() => setPage('terms')} className="text-gray-300 hover:text-white font-bold">Terms of Use</button>
                    </div>
                    <p className="text-xs text-gray-500">&copy; {new Date().getFullYear()} VA Claims Pro. All Rights Reserved. <br/>This site is not affiliated with the U.S. Department of Veterans Affairs.</p>
                </div>
            </footer>
        </div>
    );
}